# Generated by Django 5.2.17 on 2026-09-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(help_text='YYYY-MM', max_length=7, unique=True)),
                ('total_inflow', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_outflow', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month_year'],
            },
        ),
        migrations.CreateModel(
            name='InactiveUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('inactive_days', models.PositiveIntegerField(default=15)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-inactive_days'],
            },
        ),
        migrations.CreateModel(
            name='ProductRiskMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('raw_metric_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='RiskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(choices=[('EMPLOYEE_APP', 'Employee App'), ('CUSTOMER_APP', 'Customer App')], db_index=True, max_length=32)),
                ('payload_json', models.JSONField()),
                ('risk_score', models.PositiveSmallIntegerField(db_index=True)),
                ('risk_level', models.CharField(choices=[('GREEN', 'Low Risk'), ('YELLOW', 'Medium Risk'), ('RED', 'Critical Risk')], db_index=True, max_length=16)),
                ('analysis_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'risk_level'], name='risks_riskl_created_cd735f_idx'), models.Index(fields=['source_app', '-created_at'], name='risks_riskl_source__d28bf2_idx')],
            },
        ),
    ]
