# Generated by Django 5.2.17 on 2026-09-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_subject',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
